kind: ApplicationDeployment
apiVersion: radapp.io/v1alpha3
metadata:
  name: demo
  namespace: default
spec:
  template: |
    import radius as rad

    param application string
    param environment string

    resource demo 'Applications.Core/containers@2023-10-01-preview' = {
      name: 'demo'
      properties: {
        application: application
        container: {
          image: 'ghcr.io/radius-project/samples/demo:latest'
          ports: {
            web: {
              containerPort: 3000
            }
          }
        }
      }
    }
