/*
Copyright 2023 The Radius Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package templates provides Bicep templates for application generation.
package templates

// AppTemplate is the Bicep template for generating the main application definition.
const AppTemplate = `// Generated by rad app generate
extension radius

@description('Specifies the environment for resources.')
param environment string

@description('Specifies the application name.')
param application string = '{{.Name}}'

resource app 'Applications.Core/applications@2023-10-01-preview' = {
  name: application
  properties: {
    environment: environment
  }
}

{{range .Resources}}
{{.BicepContent}}
{{end}}

{{range .Containers}}
{{.BicepContent}}
{{end}}
`

// ContainerTemplate is the Bicep template for generating container resources.
const ContainerTemplate = `resource {{.ResourceName}} 'Applications.Core/containers@2023-10-01-preview' = {
  name: '{{.Name}}'
  properties: {
    application: app.id
    container: {
      image: '{{.Image}}'
    }
  }
}
`

// ResourceTemplate is the Bicep template for generating resource definitions.
const ResourceTemplate = `resource {{.ResourceName}} '{{.RadiusType}}@2023-10-01-preview' = {
  name: '{{.Name}}'
  properties: {
    application: app.id
    environment: environment
    recipe: {
      name: '{{.Recipe}}'
    }
  }
}
`
