/*
Copyright 2023 The Radius Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package generator

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestValidator_Name(t *testing.T) {
	v := NewValidator()
	assert.Equal(t, "validate_app_definition", v.Name())
}

func TestValidator_Description(t *testing.T) {
	v := NewValidator()
	assert.Contains(t, v.Description(), "Validates")
}

func TestValidator_Validate_ValidBicep(t *testing.T) {
	v := NewValidator()

	bicep := `// Generated by rad app generate
extension radius

@description('Specifies the environment for resources.')
param environment string

@description('Specifies the application name.')
param application string = 'myapp'

resource app 'Applications.Core/applications@2023-10-01-preview' = {
  name: application
  properties: {
    environment: environment
  }
}
`

	result := v.Validate(bicep)
	require.NotNil(t, result)
	assert.True(t, result.Valid)
	assert.Empty(t, result.Errors)
}

func TestValidator_Validate_EmptyContent(t *testing.T) {
	v := NewValidator()

	result := v.Validate("")
	require.NotNil(t, result)
	assert.False(t, result.Valid)
	assert.Len(t, result.Errors, 1)
	assert.Contains(t, result.Errors[0].Message, "empty")
}

func TestValidator_Validate_WhitespaceOnly(t *testing.T) {
	v := NewValidator()

	result := v.Validate("   \n\t  ")
	require.NotNil(t, result)
	assert.False(t, result.Valid)
	assert.Len(t, result.Errors, 1)
}

func TestValidator_Validate_MissingExtension(t *testing.T) {
	v := NewValidator()

	bicep := `param environment string

resource app 'Applications.Core/applications@2023-10-01-preview' = {
  name: 'myapp'
  properties: {
    environment: environment
  }
}
`

	result := v.Validate(bicep)
	require.NotNil(t, result)
	assert.False(t, result.Valid)
	assert.NotEmpty(t, result.Errors)

	hasExtensionError := false
	for _, err := range result.Errors {
		if err.Message == "Missing 'extension radius' declaration" {
			hasExtensionError = true
			break
		}
	}
	assert.True(t, hasExtensionError, "expected error about missing extension radius")
}

func TestValidator_Validate_UnbalancedBraces(t *testing.T) {
	v := NewValidator()

	bicep := `extension radius

param environment string

resource app 'Applications.Core/applications@2023-10-01-preview' = {
  name: 'myapp'
  properties: {
    environment: environment
`

	result := v.Validate(bicep)
	require.NotNil(t, result)
	assert.False(t, result.Valid)

	hasBraceError := false
	for _, err := range result.Errors {
		if err.Message == "Unbalanced braces: 2 unclosed" {
			hasBraceError = true
			break
		}
	}
	assert.True(t, hasBraceError, "expected error about unbalanced braces")
}

func TestValidator_Validate_TODOWarning(t *testing.T) {
	v := NewValidator()

	bicep := `extension radius

param environment string

resource container 'Applications.Core/containers@2023-10-01-preview' = {
  name: 'api'
  properties: {
    container: {
      image: 'TODO: api'
    }
  }
}
`

	result := v.Validate(bicep)
	require.NotNil(t, result)
	assert.True(t, result.Valid)
	assert.NotEmpty(t, result.Warnings)

	hasTODOWarning := false
	for _, w := range result.Warnings {
		if w == "Content contains TODO placeholders that need to be replaced" {
			hasTODOWarning = true
			break
		}
	}
	assert.True(t, hasTODOWarning, "expected warning about TODO placeholders")
}

func TestValidator_InputOutputSchemas(t *testing.T) {
	v := NewValidator()

	inputSchema := v.InputSchema()
	assert.NotNil(t, inputSchema)
	assert.Contains(t, string(inputSchema), "bicepContent")

	outputSchema := v.OutputSchema()
	assert.NotNil(t, outputSchema)
	assert.Contains(t, string(outputSchema), "valid")
}
